### ISSUE TITLE
rbenv should not warn about "extraneous" ruby- prefix

### ISSUE THREAD

**Issue by konklone** [sstephenson/rbenv#543]
If you use a version of `ruby-2.1.0`, rbenv emits a warning to console:

```
warning: ignoring extraneous `ruby-' prefix in version `ruby-2.1.0'
         (set by /home/eric/space/rehttp/.ruby-version)
```

As discussed [in this thread](https://github.com/rehttp/rehttp/pull/1), rbenv's behavior is not consistent with other Ruby managers like `chruby`. There should be no effect on console output if someone's trying to disambiguate their use of MRI from rubinius or jruby or something.

**Comment by pasviegas** [comment]
+1 to have a standardized file [interpreter]-[version]

**Comment by seandilda** [comment]
+1 for doing something to allow me to work on a joint project with users using other version managers without having to look at warnings all day.

From my point of view, this is a huge issue.  The sad thing is the annoyance level is stopping my work as I try to figure out what's going on, and now I see the best option is to hack my local install even though there's been a pending pull request for 3 months.

**Comment by jaredrhine** [comment]
Rubymine is what caused me to look up this issue again. My team reverted the "ruby-" removal I added last year, because we're now on Ruby 2.1 and Rubymine won't work (find the right environment) without the ruby- prefix but my issue is "just a warning". So yeah, they win the "ruby-" argument for now.

I support using warning messages to change people's behavior, and am pleased that earlier work between rbenv/rvm/chruby teams reached the current consensus. But in this case, the warning is pointed at someone who is already supporting the decision. I'm certainly not going to change away from rbenv over this, so my options do seem limited to editing rbenv directly.

sstephenson is supportive of removing the warning: https://github.com/sstephenson/rbenv/pull/650#issuecomment-63144333

Give a shout out if anyone needs a PR for the warning removal discussed in #650, but let's assume we're just waiting on a committer to find a spare moment. Thanks for continuing to field this aesthetic issue and evolving the decision through discussion here.

**Comment by mislav** [comment]
Alright @sstephenson should we remove the warning completely in the next major version? https://github.com/sstephenson/rbenv/pull/650#issuecomment-63144333

**Comment by sstephenson** [comment]
Yes please!

**Comment by leehambley** [comment]
Fuel for the fire, I "fixed" the warning for my team (terminal/vim user personally), and found that Rubymine for my team was broken.

I'm happy that it was decided to remove the warning. Thanks!

**Comment by bobbytables** [comment]
Any updates on this?

**Comment by mislav** [comment]
@bobbytables This has been applied to master. Feel free to use master version of rbenv to get this feature, or please wait until next release thanks

**Comment by pr0d1r2** [comment]
If anyone still has this warning (and have this file changing in your repo) you can use adaptive solution (based on https://github.com/rbenv/rbenv/issues/543#issuecomment-33978268) from https://github.com/pr0d1r2/ruby_dev_shell_aliases/blob/master/rbenv_ignore_extraneous_ruby_prefix_warning.sh which I just pushed.
