### ISSUE TITLE
rbenv ruby shim destroys environment vars?

### ISSUE THREAD

**Issue by chino** [sstephenson/rbenv#683]
If I try to set for instance `IFS` to something different the shims seem to reset the value.

**Comment by mislav** [comment]
How does it manifest? Where are you setting IFS yourself and how are you finding it being changed? Can you share some code so I can reproduce?

**Comment by chino** [comment]
I believe it's simply the result of the fact that the shim is a shell script and bash will do tons of modifications to the environment.

```
~ $ IFS=foo ruby -e 'puts ENV["IFS"].inspect'
" \t\n"
```

Basically any environment variable that bash or the shim would modify would bleed into the program.

At least from my perspective that makes shim's a non transparent technique to use.

I wonder if there is a way to make the script behave more like it's being `source`'d instead...

**Comment by mislav** [comment]
Thanks for letting us know. Apart from setting some `RBENV_*` variables, we don't want to actually mutate any of the user's existing environment, including IFS. I'm pretty sure we never `export IFS`, though, so I'm not sure how the environment variable bled into the subprocess.

Since IFS is not really meant to be exported/inherited from the environment, I'm pretty sure that what you're experiencing is due to the fact that rbenv is a bash script that executes `ruby` eventually. But, because it was a bash script, it resets the IFS. This has nothing to do with rbenv:

```sh
$ IFS=foo /usr/bin/ruby -e 'p ENV["IFS"]'
"foo"

$ IFS=foo bash -c '/usr/bin/ruby -e "p ENV[\"IFS\"]"'
" \t\n"
```

Notice that I skip rbenv completely in the above example, but in the 2nd example I invoke `ruby` through a bash instance and it resets IFS.

So this isn't an rbenv problem, because we're doing nothing wrong. It's going to affect every case where a bash script wraps the ruby interpreter, and only for IFS and a couple of other magic variables that bash sets dynamically.

I'm not terribly concerned about this. IFS is not something that is designed to propagate through subprocesses. For most of our users' scripting needs, rbenv is transparent enough.

**Comment by chino** [comment]
Right I'm aware that it's bash.  Would be cool though if there was a way around it.  In this particular case I was just making a script where IFS was the perfect name and already well known so required no explanation.  

Thought I'd bring it up.

Would be cool if bash supported an option where it acted more like a sub shell and didn't modify anything.

**Comment by chino** [comment]
Or I guess a generic posix type feature so it would work with most shells.
