### ISSUE TITLE
shims not installed for current ruby should still work?

### ISSUE THREAD

**Issue by chino** [sstephenson/rbenv#684]
Shims appear to exist even if the current ruby/bundle doesn't need it.

This causes causes the shim to bail out with `rbenv: xxx not found` which it should really fall back to whatever is in `$PATH`.

**Comment by mislav** [comment]
Try calling `rbenv rehash`. If a particular shims still exists and you don't want it, use `rbenv whence {name}` with the name of the executable to find which Ruby versions still contain the executable in their bin directories. Then, remove those binstubs, and call `rbenv rehash` again. The shim should be gone now, because no Ruby version references it anymore.

**Comment by chino** [comment]
Ah so `rbenv whence` partly helps me with #685.

If this was extended to (or already supports) search across `~/.rbenv/bundles` that would be perfect...

The real problem here for me is that a specific ruby may have the binary (on purpose) or a bundle in my FS may have one (that is referenced in ~/.rbenv/bundles) BUT my current rbenv version does not.  Hence the shim is called and fails.  What I would rather it do is still be able to fall back to whatever is in my `$PATH`.

A good example of why I even care about this is the chef omnibus installer installs to /opt/chef while:

- In a specific rbenv setup I might be playing around with the gem based chef
- I might have chef cloned to git where I'm working on it and bundler has picked it up and hence it's in my ~/.rbenv/bundles
- When I run test-kitchen on chef repos it seems to install things like chef/knife which causes it also to be in ~/.rbenv/bundles

Those are great features to have but it would be nice if the shim could just fall back to `$PATH`.

**Comment by mislav** [comment]
`~/.rbenv/bundles` is not a location supported by core rbenv functionality. I suspect you're using a plugin.

I can't really provide support for plugin usage because I don't know how other plugins work. You should seek support with the plugin author. I don't recommend using rbenv plugins that "integrate" with Bundler because of precisely these kind of hard-to-debug problems.  See [rbenv wiki on Bundler's binstubs](https://github.com/sstephenson/rbenv/wiki/Understanding-binstubs#bundler-generated-binstubs) for a solution that doesn't require any special rbenv integration.

**Comment by chino** [comment]
Ignoring the bundles doesn't the issue still stand?

If a ruby version that I'm not currently set too forces a shim to exist (which may be desired?) and that shim doesn't allow me to fall back to my $PATH in other versions.

**Comment by mislav** [comment]
Yes, that could be an issue for some situations. Follow issue #187 for discussion and potential solution in the future. You can try https://github.com/yyuu/rbenv-which-ext

**Comment by chino** [comment]
Thanks.

**Comment by chino** [comment]
For what it's worth `rbenv-which-ext` worked for me including with the `rbenv-binstubs` plugin.
