### ISSUE TITLE
Shims not created – and subsequently deleted when I'd created them manually

### ISSUE THREAD

**Issue by balinterdi** [sstephenson/rbenv#686]
I accidentally nuked the ~/.rbenv/versions from my machine so I started with a clean slate.

I installed 2.0.0-p594 by `rbenv install 2.0.0-p594`, all went well.

I then did `gem install bundler` and `gem install middleman`.

I proceeded with `rbenv rehash` so that the shims for the executables for both of these are created. However, the shims are not created in `~/.rbenv/shims`. I opened the `rbenv-rehash` script to see what it does and then created the links manually by 

    ln -f ~/.rbenv/versions/2.0.0-p594/lib/ruby/gems/2.0.0/gems/middleman-core-3.3.7/bin/middleman middleman

I did likewise for bundler.

Furthermore, the shims are deleted by something on a regular basis (this has happened three times in the last 15 minutes and I did not run `rbenv rehash` during this time) so I can't really use any of the executables for the gems.

Taking my cue [from the binstubs wiki](https://github.com/sstephenson/rbenv/wiki/Understanding-binstubs), I think the middleman and bundler executables should be present in `~/.rbenv/versions/2.0.0-p594/bin` but they are not there either.

Can you point at what I am doing wrong?

**Comment by mislav** [comment]
Sorry you're having trouble. You shouldn't be required to create any hard links by hand. The shims directory will get purged and recreated every time you call `rbenv rehash` or open a new terminal window; that's why your manual changes were so short-lived.

The primary problem, which you figured out by yourself, is that the executables you want were never put in `~/.rbenv/versions/2.0.0-p594/bin`. rbenv doesn't put them there; they're supposed to be created there by the `gem install` process.

I'm not sure what went wrong, but maybe when you did `gem install bundler` you didn't have the `2.0.0-p594` version selected as the current version at the time? Maybe you've installed the gems in the system-wide Ruby installation instead?

You can check the list of installed gems with `~/.rbenv/versions/2.0.0-p594/bin/gem list`. If the Bundler gem is already installed there, you can force recreating its binstub with `gem pristine bundler`.

**Comment by balinterdi** [comment]
Mislav, thank you so much for your detailed answer.

I don't know why the binaries were not installed in the `~/.rbenv/versions/2.0.0-p594/bin` folder since I am sure that ruby version was selected when I installed the gems but when I did `gem pristine middleman-core` (and likewise for bundler) they were copied there.

Subsequently `rbenv rehash` works fine, it creates the shims and everything works perfectly. Thank you for teaching me about `gem pristine` and solving my problem!
