### ISSUE TITLE
rbenv: version `system' is not installed

### ISSUE THREAD

**Issue by erwin16** [sstephenson/rbenv#693]
when I try to run a migration from within a release ( for testing purpose) I get this message : 
 
    ubuntu@ip-172-31-11-0:/srv/simpleapp/releases/20150213170350$ rake db:migrate
    rbenv: version `system' is not installed

however when I run this, it shows the installed version ...

    rbenv versions
      * system (set by /home/ubuntu/.rbenv/version)
       2.2.0

what's wrong ?

**Comment by mislav** [comment]
"system" version is the default global version for rbenv if you've never specified a global version otherwise. "system" refers to the Ruby version that might be present on your system that's not managed by rbenv, such as `/usr/bin/ruby` as installed by apt-get.

However, it's also possible that the "system" Ruby version is not present on the system, such as in the case of when Ruby package was never installed. I don't know why `rbenv versions` would list "system" in that case, because it shouldn't.

Generally I advise against using the system Ruby for projects. The fix you should take is twofold:

1. Select the global version of Ruby to be used as a default with `rbenv global 2.2.0`
2. Select the local version of Ruby to be used for this project with:

    ```
    cd /srv/simpleapp/releases/20150213170350
    rbenv local 2.2.0
    ```

Step (2) will create a `.ruby-version` file inside this project that signals to rbenv that it should always use this specific Ruby version inside this project. We recommend that you add a `.ruby-version` file to all your individual projects and keep that in version control.

**Comment by raynix** [comment]
Step 1 fixed my problem. Thanks.

**Comment by willemtoledano** [comment]
Step 1 fixed mine too, thank you.
