### ISSUE TITLE
gem error with rbenv

### ISSUE THREAD

**Issue by Draveness** [sstephenson/rbenv#714]
I can use gem in system version but when I change the version to 2.2.0.

```
>  gem upgrade --system
ERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command upgrade
```

```
> gem install rake
ERROR:  Could not find a valid gem 'rake' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - no such name (https://api.rubygems.org/specs.4.8.gz)
```

But with system version, this does not happen.

**Comment by mislav** [comment]
1. How do you feel that this is a bug with rbenv, which only switches Ruby versions and isn't responsible for them working?
2. How did you install Ruby 2.2.0?
3. What is your `gem --version` on Ruby 2.2.0?
4. Does the same error happen every time?

**Comment by Draveness** [comment]
1. I do not know actually what causes this problem. 
2. rbenv install 2.2.0.
3. gem --version 2.4.5
4. Yes, It happens every time

**Comment by tolbkni** [comment]
Same here with rbenv install 2.2.2

**Comment by mislav** [comment]
I have googled the error message; it seems pretty common and smells like a networking issue. [It is raised](https://github.com/rubygems/rubygems/blob/v2.4.5/lib/rubygems/remote_fetcher.rb#L282-L284) when the DNS entry for a hostname to fetch gemspecs from couldn't be resolved.

I really don't think this is caused by rbenv or Ruby installation in any way. Please try to check your DNS settings and HTTP proxy settings. I'm sorry I couldn't be of more help.
