### ISSUE TITLE
$RBENV_ROOT not set in plugin's environment as expected

### ISSUE THREAD

**Issue by jasonkarns** [sstephenson/rbenv#715]
We are encountering an issue with the rbenv-update plugin wherein `$RBENV_ROOT` isn't set within the plugin's environment. The wiki [states](https://github.com/sstephenson/rbenv/wiki/Authoring-plugins#environment) that rbenv ensures `$RBENV_ROOT` will be set as part of the plugin's environment. While debugging this between one system that works and another that doesn't, the only differing behavior seems to be that rbenv is invoking `rbenv-sh-update` instead of `rbenv-update`.

Both setups have rbenv installed into `~/.rbenv`, without `$RBENV_ROOT` set. gist for [both debug logs](https://gist.github.com/jasonkarns/b134911bf20bd3356e45) ([one that works](https://gist.github.com/jasonkarns/b134911bf20bd3356e45#file-working-sh)) and ([one that doesn't](https://gist.github.com/jasonkarns/b134911bf20bd3356e45#file-broken-sh))

Note that the first meaningful different is between https://gist.github.com/jasonkarns/b134911bf20bd3356e45#file-broken-sh-L48 and https://gist.github.com/jasonkarns/b134911bf20bd3356e45#file-working-sh-L46. For some reason, on the machine that doesn't work, rbenv thinks the command is `sh-update`.

Does anyone have any thoughts on this? Why is `rbenv update` invoking `rbenv-sh-update` instead of `rbenv-update`?

**Comment by mislav** [comment]
Sorry for late reply. RBENV_ROOT will always be available from your plugins.

The issue here it seems to be that [`rbenv-sh-update` executable](https://github.com/jasonkarns/rbenv-update/blob/520aa9e8df774bf3b8a364063be12dc5ec373806/bin/rbenv-sh-update#L5) is improperly authored. You see, `rbenv-sh-*` executables are going to be invoked from interactive shells for commands that have a `sh-*` equivalent. That executable is supposed to output shell syntax that is to be eval'd in the current user's interactive shell.

Now, the `rbenv-sh-update` output will contain absolute path to `rbenv-update` executable within the plugin. However, this will be executed outside of typical rbenv plugin environment, and you should never invoke rbenv-* executables directly without going through main `rbenv` executable that prepares the environment.

This is kind of hard to explain and I'm sorry I'm not doing a great job at it. In short, the `rbenv-sh-update` command is not well authored and should output `command rbenv update` instead of `$(which rbenv-update)`.
