### ISSUE TITLE
Merge rbenv install into rbenv

### ISSUE THREAD

**Issue by martinbrown** [sstephenson/rbenv#723]
Please just take the rbenv install plugin into rbenv as a native command.  It's really annoying having to download a separate plugin for such a basic/essential feature of a ruby version manager.

**Comment by include** [comment]
ahh so thats why I don't find the 'install' sub command... can you send me please info about that plugin please?

**Comment by mislav** [comment]
It's [described here](https://github.com/sstephenson/rbenv#installing-ruby-versions).

Some people want to use different Ruby installers than ruby-build project, or use no installers and compile their Rubies manually. I know that it can be burden to remember to install the plugin, but for us it makes sense to maintain the two projects separately because they're on very different release cycles.
