### ISSUE TITLE
can't install ruby 2.2.1 on ubuntu 14.04

### ISSUE THREAD

**Issue by benams** [sstephenson/rbenv#732]
I'm trying to install rvm 2.2.1 with: rbenv install 2.2.1, after a few moments the installation process is stopped and I see error mesaages:

```
Installing ruby-2.2.1...

BUILD FAILED (Ubuntu 14.04 using ruby-build 20150506)

Inspect or clean up the working tree at /tmp/ruby-build.20150510184835.8351
Results logged to /tmp/ruby-build.20150510184835.8351.log

Last 10 log lines:
make[3]: Leaving directory `/tmp/ruby-build.20150510184835.8351/ruby-2.2.1/ext/fiddle/libffi-3.2.1'
linking shared-object fiddle.so
/usr/bin/ld: ./libffi-3.2.1/.libs/libffi.a(raw_api.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
./libffi-3.2.1/.libs/libffi.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [../../.ext/x86_64-linux/fiddle.so] Error 1
make[2]: Leaving directory `/tmp/ruby-build.20150510184835.8351/ruby-2.2.1/ext/fiddle'
make[1]: *** [ext/fiddle/all] Error 2
make[1]: Leaving directory `/tmp/ruby-build.20150510184835.8351/ruby-2.2.1'
make: *** [build-ext] Error 2
```

My system details are: 
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

**Comment by hsbt** [comment]
@benams Please try with Ruby 2.2.2

**Comment by mislav** [comment]
Yes, please upgrade to 2.2.2 which should take care of these issues. Alternatively, peruse some of the [existing ruby-build threads mentioning the same issue](https://github.com/sstephenson/ruby-build/issues?utf8=%E2%9C%93&q=is%3Aissue+libffi). I'm going to close this, but if you have any more problems please reopen the issue, this time in the appropriate "ruby-build" repository rather than "rbenv" one. Thanks
