### ISSUE TITLE
performance: use "source ..." instead of forking bash multiple times

### ISSUE THREAD

**Issue by blueyed** [sstephenson/rbenv#736]
As mentioned initially in https://github.com/sstephenson/rbenv/issues/70#issuecomment-93142268:

`bash` gets invoked a lot during the rbenv process, where it would be probably faster to source the different parts instead.

I've started some proof-of-concept, where `$(source "$(command -v libexec-script)" args)` is used instead of `$(libexec-script args)`, in the pyenv sibling: https://github.com/yyuu/pyenv/issues/356 for the issue (https://github.com/yyuu/pyenv/pull/357 for the PR/code).

I think this is also interesting for rbenv, and would be good to keep the difference between rbenv and pyenv small.

https://github.com/yyuu/pyenv/issues/356#issue-68534848 has some benchmark results: it makes `python -V` with pyenv twice as fast on my machine.

What do you think?

**Comment by mislav** [comment]
@sstephenson's original idea about rbenv utils being implemented as individual executables that each do only one thing is great from a Unix philosophical standpoint but yeah, as we both noticed it doesn't perform well. I'd be interested to see detailed benchmarks about how much we can save by sourcing the functions, but even with a performance benefit that doesn't mean I would accept the change. It's very likely that it will make the code more gross and that it will be a departure from rbenv's core philosophy.

I'd rather that we re-implement rbenv as a precompiled binary written in Go, for example. We could make the fact that it deals with `ruby` executables and looks for `.ruby-version` filenames configurable from the outside, so that you could use the same binary to look for `python` executable and `.python-version` file in the current directory. Then we could consolidate all of the rbenv, pyenv, phantomenv, goenv projects that basically replicate what rbenv does with small tweaks.

**Comment by mislav** [comment]
Proof-of-concept of configurable rbenv in Go: https://github.com/mislav/everyenv

@blueyed @yyuu @joshfriend Please take a look at [`config/values.go`](https://github.com/mislav/everyenv/blob/06c2d11ad76859e523cf14915532fdad0f0c99fa/config/values.go#L9-L12). These could be configured from the outside to handle `.python-version` files, respect `PYENV_VERSION` environment variable etc. I still need to work on the configuration aspect— right now the values are hardcoded, but they could be easily set from environment variables. I would appreciate your input. Thanks

**Comment by blueyed** [comment]
Awesome!

Maybe Root should get expanded at runtime, supporting tilde-expansion?

One big feature of pyenv is also to activate multiple Python versions at once - will the be supported?

**Comment by mislav** [comment]
`Root` does get expanded at runtime supporting `$HOME` expansion, but it doesn't support tilde `~` expansion.

I'm not sure what you mean by activating multiple Python versions, but I would appreciate if you opened an issue on https://github.com/mislav/anyenv and described your use case. I want to understand what are some specifics of managing things other than Ruby versions.

Thanks! I will close this for now, because sourcing scripts within rbenv might be a huge project that I'm unlikely to embark on right now.

**Comment by blueyed** [comment]
> sourcing scripts within rbenv might be a huge project that I'm unlikely to embark on right now

There is a patch for pyenv already, that could be adopted.

But I see that it is not really necessary now anymore, given anyenv.

**Comment by mislav** [comment]
> There is a patch for pyenv already, that could be adopted.

Feel free to cc me in discussions about the patch, esp. if there are benchmarks.

> But I see that it is not really necessary now anymore, given anyenv.

Well, it's not like anyenv is going to replace rbenv right away, but I think I'm done trying to speed up things in bash.

**Comment by blueyed** [comment]
>> There is a patch for pyenv already, that could be adopted.

> Feel free to cc me in discussions about the patch, esp. if there are benchmarks.

We're trying to keep pyenv as similar as possible to rbenv, to make merging things easier, so that patch might not fly for pyenv then.  OTOH we've introduced a common merge point a while ago, which should make it easier to have this difference.

I've opened an issue for multiple versions support at: https://github.com/mislav/anyenv/issues/3.
