### ISSUE TITLE
Shell stuck in loop : command not found

### ISSUE THREAD

**Issue by bradbergeron-us** [sstephenson/rbenv#754]
/usr/local/Cellar/rbenv/0.4.0/libexec/../completions/rbenv.bash:16: command not found: complete
                                                                                
[Process completed]

![image](https://cloud.githubusercontent.com/assets/8945799/8565433/e95f1c02-2523-11e5-8165-5bafd6f09731.png)

Is there a quick fix for this? ... Kinda need terminal back sooner the better! 

Let me know what else I can provide.

Thanks!

**Comment by putztzu** [comment]
Your initialization command is not working. One way to implement is to modify the BASH shell profile as described in the official documentation

```
Add rbenv init to your shell to enable shims and autocompletion.

$ echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
```

Another simpler but trickier way I implemented is to create a "sh" script which contains this and the PATH command and place it in /etc/profile.d/

The advantage of my implementation is that the profile modifications are applied to all Users which might login to the machine, but since the default location of rbenv is in a /home/user/ directory, you'd also need to modify $HOME to a full, fixed path to implement fully.

But, if you follow the documentation (in particular what I quoted above), you should be OK, too.

HTH

**Comment by mislav** [comment]
Thanks @putztzu.

@bradbergeron-us It would help us a great deal if you actually shared how you tried to configure your shell. Sharing this would be a good start: `grep -i rbenv ~/.bash_profile`

**Comment by bradbergeron-us** [comment]
export RBENV_ROOT=/usr/local/var/rbenv
If which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

**Comment by mislav** [comment]
@bradbergeron-us That all seems right. Which bash version do you have? `$BASH --version`

Does the `complete` builtin exist? Check with `help complete`

Is it possible that your bash was compiled without completion support?

**Comment by mislav** [comment]
Closing due to lack of info. If you're still having problems, please update with more info! Also try to upgrade rbenv to newest version by means of `brew upgrade rbenv --HEAD`.

**Comment by dkav** [comment]
I ran into this problem when initializing in zsh on OS X 10.11. I had to add 
```
autoload bashcompinit
bashcompinit
```
before sourcing.
