### ISSUE TITLE
rbenv use global specified ruby version not work on OS X EI

### ISSUE THREAD

**Issue by Matrixbirds** [sstephenson/rbenv#823]
![rbenv_issues_1](https://cloud.githubusercontent.com/assets/9990676/11215154/cede41e0-8d7f-11e5-8bcc-45910db19119.jpg)
![rbenv_issues_2](https://cloud.githubusercontent.com/assets/9990676/11215155/cf16a94a-8d7f-11e5-892c-be9ed6120d82.jpg)
I use zsh and the `bundle install` use system ruby version not use `2.2.3` or `2.2.2`

**Comment by mislav** [comment]
Hi there! `rbenv global 2.2.2` indeed sets the global version, but in your case that didn't have any effect since you seem to have a `~/.ruby-version` file that takes precedence, because it's considered a "local" version file (local files are searched in your project's directory and all parent directories).

My recommendation is to `rm ~/.ruby-version`.

**Comment by Matrixbirds** [comment]
Very very nice solution 😁. 
If rbenv can give me an warning will be very cool.
Could u add the feature to give the warning message in this situation?

**Comment by mislav** [comment]
Hmm, I'm not sure what kind of warning should I add.

If people want to create a `.ruby-version` file in their home, they should be allowed to do so. In that case, I assume that they know what they're doing and that a "local" version always takes precedence over "global" version.
